# file: roles/mariadb/tasks/main.yml

#
# This playbook installed and configure the mariadb server.
#

# MariaDB Server
- name: Install mariadb server
  apt: name={{item}} state=installed
  with_items:
    - mariadb-server
    - mariadb-client
    - python-mysqldb

# Setup MariaDB
- name: Change case-sensetiv for mariadb
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^lower_case_table_names = 1'
    insertafter: '^[mysqld]'
    line: 'lower_case_table_names = 1'
    backup: yes
  notify:
    - restart mariadb
- name: Create mariadb user sqladmin
  mysql_user:
    name: sqladmin
    password: admin
    priv: '*.*:ALL'
    state: present
- name: Create mariadb database kaa
  mysql_db:
    name: kaa
    collation: utf8_general_ci
    encoding: utf8
    state: present

# Install phpmyadmin
- name: Install phpmyadmin
  apt:
    name: phpmyadmin
- name: Install phppgadmin
  apt:
    name: phppgadmin

# Enable phpmyadmin
- name: Adding phpmyadmin in apache2
  file:
    src: /etc/phpmyadmin/apache.conf
    dest: /etc/apache2/conf-available/phpmyadmin.conf
    owner: root
    group: root
    state: link
- name: Enabling phpmyadmin in apache2
  file:
    src: /etc/apache2/conf-available/phpmyadmin.conf
    dest: /etc/apache2/conf-enabled/phpmyadmin.conf
    owner: root
    group: root
    state: link
  notify:
    - restart apache2

