# file: roles/apache2/tasks/main.yml

#
# This playbook installed and configure the apache server with php.
#

# Web-Server
- name: Install apache httpd2
  apt:
    name: apache2
- name: Install PHP
  apt:
    name: php
- name: Install libapache2-mod-php
  apt:
    name: libapache2-mod-php

# Adding groups to user
- name: Adding apache group for sysadm
  user:
    name: sysadm
    append: yes
    groups: www-data
- name: Adding apache group for iot
  user:
    name: iot
    append: yes
    groups: www-data

# Linking directories
- name: Chown html
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
- name: Chown html
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
- name: Creating symlink html for sysadm
  file:
    src:  /var/www/html
    dest: /home/sysadm/html
    owner: sysadm
    group: sysadm
    state: link
- name: Creating symlink html for iot
  file:
    src:  /var/www/html
    dest: /home/iot/html
    owner: iot
    group: iot
    state: link
