## Spring Configuration ##
spring:
  # Application
  application:
    name: @project.name@
    version: @project.version@

## Logging ##
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    me.wirries.weatheriotshowcase.sensor: DEBUG

## Sensor Window ##
window:
  height: 480
  width: 640
  resizeable: false

## Alive-Server ##
server:
  ipAddress: @server.ipAddress@

## REST API ##
rest:
  url: http://localhost:8080/rest/message/temperature

## MQTT ##
mqtt:
  url: 'tcp://@server.ipAddress@:1883'
  topic: weather
