# file: showcase.yml

#
# This playbook configures the IoT-Server. The host group iotservers will used.
# It must be run as privileged user.
#
- hosts: showcase
  become: yes
  become_method: sudo
  roles:
    - common
    - java
    - postfix
    - apache2
    - tomcat
    - mariadb
    - mqtt
